{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agamenon.fullname" . }}-auth
  labels:
    {{- include "agamenon.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
{{- end }}
---
{{- if and (eq .Values.storage.backend "postgres") (not .Values.storage.postgres.existingSecret) .Values.storage.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agamenon.fullname" . }}-postgres
  labels:
    {{- include "agamenon.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.storage.postgres.password | b64enc | quote }}
{{- end }}
